on:
  pull_request:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target_type:
          - server
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v5
        with:
          path: |
            ~/AppData/Local/.xmake
            .xmake
          key: xmake-${{ runner.os }}-${{ matrix.target_type }}-${{ hashFiles('xmake.lua', 'src/**') }}
          restore-keys: |
            xmake-${{ runner.os }}-${{ matrix.target_type }}-
            xmake-${{ runner.os }}-

      - run: xmake repo -u

      - run: xmake f -a x64 -m release -p windows -v --target_type=${{ matrix.target_type }} -y

      - run: xmake -v -y

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}-${{ matrix.target_type }}-windows-x64
          path: bin/
